"""add unique constraint to data_processing_pipe2d

Revision ID: 348db3f79d46
Revises: 8c31485a7982
Create Date: 2026-07-07 15:33:52.547067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348db3f79d46'
down_revision: Union[str, None] = '8c31485a7982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_collection_run', 'data_processing_pipe2d', [
                                'collection_name', 'run_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_collection_run',
                       'data_processing_pipe2d', type_='unique')
    # ### end Alembic commands ###
