"""add onsite_processing_status table

Revision ID: 4f4653b59742
Revises: 22f42432243c
Create Date: 2025-08-13 13:22:16.763138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4653b59742'
down_revision: Union[str, None] = '22f42432243c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onsite_processing_status',
    sa.Column('pfs_visit_id', sa.Integer(), autoincrement=False, nullable=False, comment='PFS visit ID'),
    sa.Column('status', sa.Integer(), nullable=True, comment='Status of processing (0=in progress, 1=completed successfully, 2=completed but failed)'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='datetime of the processing start'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='datetime of the status update'),
    sa.PrimaryKeyConstraint('pfs_visit_id'),
    sa.UniqueConstraint('pfs_visit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onsite_processing_status')
    # ### end Alembic commands ###
