"""fix column type of flux_cal_qa

Revision ID: 8c31485a7982
Revises: f6f47983358a
Create Date: 2026-07-06 16:01:01.784869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c31485a7982'
down_revision: Union[str, None] = 'f6f47983358a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flux_cal_qa', 'merged_filter',
                    existing_type=sa.REAL(),
                    type_=sa.String(),
                    existing_comment='TBD',
                    existing_nullable=True)
    op.alter_column('flux_cal_qa', 'merged_color_filters',
                    existing_type=sa.REAL(),
                    type_=sa.String(),
                    existing_comment='TBD',
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flux_cal_qa', 'merged_color_filters',
                    existing_type=sa.String(),
                    type_=sa.REAL(),
                    existing_comment='TBD',
                    existing_nullable=True)
    op.alter_column('flux_cal_qa', 'merged_filter',
                    existing_type=sa.String(),
                    type_=sa.REAL(),
                    existing_comment='TBD',
                    existing_nullable=True)
    # ### end Alembic commands ###
