"""update 20240220

Revision ID: c16e832efa75
Revises: d43f1cb6934e
Create Date: 2024-02-20 14:03:19.526998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16e832efa75'
down_revision: Union[str, None] = 'd43f1cb6934e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noise', sa.Column('wavelength_ref', sa.REAL(), nullable=True, comment='the reference wavelength to measure the sky background noise (nm)'))
    op.add_column('seeing', sa.Column('wavelength_ref', sa.REAL(), nullable=True, comment='the reference wavelength to measure the seeing (nm)'))
    op.add_column('sky', sa.Column('agc_background_mean', sa.REAL(), nullable=True, comment='the mean agc image background level averaged over the FoV/fibers (counts)'))
    op.add_column('sky', sa.Column('agc_background_median', sa.REAL(), nullable=True, comment='the median agc image background level averaged over the FoV/fibers (counts)'))
    op.add_column('sky', sa.Column('agc_background_sigma', sa.REAL(), nullable=True, comment='the sigma of the agc image background level (counts)'))
    op.add_column('throughput', sa.Column('wavelength_ref', sa.REAL(), nullable=True, comment='the reference wavelength to measure the total throughput (nm)'))
    op.alter_column('throughput', 'throughput_mean',
               existing_type=sa.REAL(),
               comment='the total throughput (mean)',
               existing_comment='the instrumental throughput (mean)',
               existing_nullable=True)
    op.alter_column('throughput', 'throughput_median',
               existing_type=sa.REAL(),
               comment='the total throughput (median)',
               existing_comment='the instrumental throughput (median)',
               existing_nullable=True)
    op.alter_column('throughput', 'throughput_sigma',
               existing_type=sa.REAL(),
               comment='the total throughput (sigma)',
               existing_comment='the instrumental throughput (sigma)',
               existing_nullable=True)
    op.add_column('transparency', sa.Column('wavelength_ref', sa.REAL(), nullable=True, comment='the reference wavelength to measure the transparency (nm)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transparency', 'wavelength_ref')
    op.alter_column('throughput', 'throughput_sigma',
               existing_type=sa.REAL(),
               comment='the instrumental throughput (sigma)',
               existing_comment='the total throughput (sigma)',
               existing_nullable=True)
    op.alter_column('throughput', 'throughput_median',
               existing_type=sa.REAL(),
               comment='the instrumental throughput (median)',
               existing_comment='the total throughput (median)',
               existing_nullable=True)
    op.alter_column('throughput', 'throughput_mean',
               existing_type=sa.REAL(),
               comment='the instrumental throughput (mean)',
               existing_comment='the total throughput (mean)',
               existing_nullable=True)
    op.drop_column('throughput', 'wavelength_ref')
    op.drop_column('sky', 'agc_background_sigma')
    op.drop_column('sky', 'agc_background_median')
    op.drop_column('sky', 'agc_background_mean')
    op.drop_column('seeing', 'wavelength_ref')
    op.drop_column('noise', 'wavelength_ref')
    # ### end Alembic commands ###
