"""remove unique consts

Revision ID: d7b6b93ef51d
Revises: e1b4a8468e3a
Create Date: 2024-04-17 12:13:27.115381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b6b93ef51d'
down_revision: Union[str, None] = 'e1b4a8468e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('seeing_agc_exposure_agc_exposure_id_key',
                       'seeing_agc_exposure', type_='unique')
    op.drop_constraint('seeing_agc_exposure_pfs_visit_id_key',
                       'seeing_agc_exposure', type_='unique')
    op.create_unique_constraint(None, 'seeing_agc_exposure', [
                                'pfs_visit_id', 'agc_exposure_id'])
    op.drop_constraint('transparency_agc_exposure_agc_exposure_id_key',
                       'transparency_agc_exposure', type_='unique')
    op.drop_constraint('transparency_agc_exposure_pfs_visit_id_key',
                       'transparency_agc_exposure', type_='unique')
    op.create_unique_constraint(None, 'transparency_agc_exposure', [
                                'pfs_visit_id', 'agc_exposure_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transparency_agc_exposure', type_='unique')
    op.create_unique_constraint(
        'transparency_agc_exposure_pfs_visit_id_key', 'transparency_agc_exposure', ['pfs_visit_id'])
    op.create_unique_constraint('transparency_agc_exposure_agc_exposure_id_key',
                                'transparency_agc_exposure', ['agc_exposure_id'])
    op.drop_constraint(None, 'seeing_agc_exposure', type_='unique')
    op.create_unique_constraint(
        'seeing_agc_exposure_pfs_visit_id_key', 'seeing_agc_exposure', ['pfs_visit_id'])
    op.create_unique_constraint(
        'seeing_agc_exposure_agc_exposure_id_key', 'seeing_agc_exposure', ['agc_exposure_id'])
    # ### end Alembic commands ###
