"""PIPE2D-1385

Revision ID: f6f47983358a
Revises: 4f4653b59742
Create Date: 2026-06-25 10:30:34.487764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6f47983358a'
down_revision: Union[str, None] = '4f4653b59742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_processing_pipe2d',
                    sa.Column('processing_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('collection_name', sa.String(
                    ), nullable=True, comment='pipe2d collection name (e.g. PFS/calib/pipe2d-1842/run28/verifyCalib.calibs.20260520a)'),
                    sa.Column('run_name', sa.String(), nullable=True,
                              comment='pipe2d RUN name (e.g. 20260521T061122Z)'),
                    sa.Column('pipe2d_version', sa.String(), nullable=True,
                              comment='pipe2d version (e.g., w.2026.20)'),
                    sa.Column('drp_qa_version', sa.String(), nullable=True,
                              comment='drp_qa version (e.g., w.2026.20)'),
                    sa.PrimaryKeyConstraint('processing_id')
                    )
    op.create_table('detector_map_qa',
                    sa.Column('processing_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('pfs_visit_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('camera_name', sa.String(length=2),
                              autoincrement=False, nullable=False),
                    sa.Column('status_type', sa.String(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.String(),
                              autoincrement=False, nullable=False),
                    sa.Column('spectrograph', sa.Integer(), nullable=True),
                    sa.Column('arm', sa.String(length=1), nullable=True),
                    sa.Column('observation_reason',
                              sa.String(), nullable=True),
                    sa.Column('dof', sa.REAL(), nullable=True),
                    sa.Column('chi2x', sa.REAL(), nullable=True),
                    sa.Column('chi2y', sa.REAL(), nullable=True),
                    sa.Column('spatial_median', sa.REAL(), nullable=True),
                    sa.Column('spatial_robust_rms', sa.REAL(), nullable=True),
                    sa.Column('spatial_weighted_rms',
                              sa.REAL(), nullable=True),
                    sa.Column('spatial_soften_fit', sa.REAL(), nullable=True),
                    sa.Column('spatial_dof', sa.REAL(), nullable=True),
                    sa.Column('spatial_num_fibers',
                              sa.Integer(), nullable=True),
                    sa.Column('spatial_num_lines',
                              sa.Integer(), nullable=True),
                    sa.Column('wavelength_median', sa.REAL(), nullable=True),
                    sa.Column('wavelength_robust_rms',
                              sa.REAL(), nullable=True),
                    sa.Column('wavelength_weighted_rms',
                              sa.REAL(), nullable=True),
                    sa.Column('wavelength_soften_fit',
                              sa.REAL(), nullable=True),
                    sa.Column('wavelength_dof', sa.REAL(), nullable=True),
                    sa.Column('wavelength_num_fibers',
                              sa.Integer(), nullable=True),
                    sa.Column('wavelength_num_lines',
                              sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['pfs_visit_id'], ['pfs_visit.pfs_visit_id'], ),
                    sa.ForeignKeyConstraint(
                        ['processing_id'], ['data_processing_pipe2d.processing_id'], ),
                    sa.PrimaryKeyConstraint(
                        'processing_id', 'pfs_visit_id', 'camera_name', 'status_type', 'description')
                    )
    op.create_table('extraction_qa',
                    sa.Column('processing_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('pfs_visit_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('camera_name', sa.String(length=2),
                              autoincrement=False, nullable=False),
                    sa.Column('fiber_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('spectrograph', sa.Integer(), nullable=True),
                    sa.Column('arm', sa.String(length=1), nullable=True),
                    sa.Column('xa', sa.REAL(), nullable=True),
                    sa.Column('pfs_arm_ave', sa.REAL(), nullable=True),
                    sa.Column('chi2', sa.REAL(), nullable=True),
                    sa.Column('chi_ave', sa.REAL(), nullable=True),
                    sa.Column('chi_med', sa.REAL(), nullable=True),
                    sa.Column('chi_std', sa.REAL(), nullable=True),
                    sa.Column('chi_at_peak', sa.REAL(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['pfs_visit_id'], ['pfs_visit.pfs_visit_id'], ),
                    sa.ForeignKeyConstraint(
                        ['processing_id'], ['data_processing_pipe2d.processing_id'], ),
                    sa.PrimaryKeyConstraint(
                        'processing_id', 'pfs_visit_id', 'camera_name', 'fiber_id')
                    )
    op.create_table('flux_cal_qa',
                    sa.Column('processing_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('pfs_visit_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('number_of_flux_standards', sa.Integer(), nullable=True,
                              comment='the number of flux standard stars to calculate the vector'),
                    sa.Column('merged_filter', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('merged_median', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('merged_sigma', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('merged_sn_median', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('merged_sn_sigma', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('imag_median', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('imag_sigma', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('merged_color_filters', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('merged_color_median', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('merged_color_sigma', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('single_median', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('single_sigma', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('single_color_median', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('single_color_sigma', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('stellar_sequence_sigma_gri', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('stellar_sequence_sigma_riz', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.Column('stellar_sequence_sigma_izy', sa.REAL(),
                              nullable=True, comment='TBD'),
                    sa.ForeignKeyConstraint(
                        ['pfs_visit_id'], ['pfs_visit.pfs_visit_id'], ),
                    sa.ForeignKeyConstraint(
                        ['processing_id'], ['data_processing_pipe2d.processing_id'], ),
                    sa.PrimaryKeyConstraint('processing_id', 'pfs_visit_id')
                    )
    op.create_table('sky_subtraction_qa_sa',
                    sa.Column('processing_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('pfs_visit_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('number_of_sky_fibers', sa.Integer(), nullable=True,
                              comment='the number of sky fibers to make the sky model'),
                    sa.Column('skysub_median_avg', sa.REAL(),
                              nullable=True, comment='TBW'),
                    sa.Column('skysub_median_under', sa.REAL(),
                              nullable=True, comment='TBW'),
                    sa.Column('skysub_median_over', sa.REAL(),
                              nullable=True, comment='TBW'),
                    sa.Column('skysub_median_abs', sa.REAL(),
                              nullable=True, comment='TBW'),
                    sa.Column('skysub_continuum_flux_fit_median', sa.REAL(), nullable=True,
                              comment='the median of residual of sky-subtracted sky spectra (electrons/nm)'),
                    sa.Column('skysub_continuum_sky_fit_median', sa.REAL(
                    ), nullable=True, comment='the median of sky spectra (electrons/nm)'),
                    sa.ForeignKeyConstraint(
                        ['pfs_visit_id'], ['pfs_visit.pfs_visit_id'], ),
                    sa.ForeignKeyConstraint(
                        ['processing_id'], ['data_processing_pipe2d.processing_id'], ),
                    sa.PrimaryKeyConstraint('processing_id', 'pfs_visit_id')
                    )
    op.create_table('sky_subtraction_qa_sa_continuum',
                    sa.Column('processing_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('pfs_visit_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('fiber_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('continuum_residual_fit', sa.REAL(), nullable=True,
                              comment='the median of residual of sky-subtracted sky spectra (electrons/nm)'),
                    sa.Column('continuum_sky_fit', sa.REAL(), nullable=True,
                              comment='the median of sky spectra (electrons/nm)'),
                    sa.ForeignKeyConstraint(['processing_id', 'pfs_visit_id'], [
                        'sky_subtraction_qa_sa.processing_id', 'sky_subtraction_qa_sa.pfs_visit_id'], ),
                    sa.PrimaryKeyConstraint(
                        'processing_id', 'pfs_visit_id', 'fiber_id')
                    )
    op.create_table('sky_subtraction_qa_sa_line',
                    sa.Column('processing_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('pfs_visit_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('fiber_id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('subtype', sa.String(), autoincrement=False, nullable=False,
                              comment='subtype of evaluation (avg/under/over/abs)'),
                    sa.Column('flux_to_sky', sa.REAL(), nullable=True,
                              comment='the ratio between residual and sky flux (percent)'),
                    sa.Column('sky_lines_num', sa.Integer(), nullable=True,
                              comment='the number of sky lines used'),
                    sa.ForeignKeyConstraint(['processing_id', 'pfs_visit_id'], [
                        'sky_subtraction_qa_sa.processing_id', 'sky_subtraction_qa_sa.pfs_visit_id'], ),
                    sa.PrimaryKeyConstraint(
                        'processing_id', 'pfs_visit_id', 'fiber_id', 'subtype')
                    )
    op.drop_table('data_processing_results')
    op.drop_table('data_processing')
    op.drop_table('sky_subtraction')
    op.drop_table('flux_calibration')
    op.drop_table('detector_map')
    op.add_column('data_qa', sa.Column('pipe2d_version', sa.String(
    ), nullable=True, comment='pipe2d version (e.g., w.2025.20)'))
    op.add_column('data_qa', sa.Column('drp_qa_version', sa.String(
    ), nullable=True, comment='drp_qa version (e.g., w.2025.20)'))
    op.add_column('data_qa', sa.Column('process_type',
                  sa.String(), nullable=True, comment='process_type'))
    op.drop_column('data_qa', 'qa_version')
    op.drop_column('data_qa', 'qa_type')
    op.alter_column('telescope', 'airmass',
                    existing_type=sa.REAL(),
                    comment='the average airmass during the exposure',
                    existing_comment='the average airmass during the exposure (deg.)',
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telescope', 'airmass',
                    existing_type=sa.REAL(),
                    comment='the average airmass during the exposure (deg.)',
                    existing_comment='the average airmass during the exposure',
                    existing_nullable=True)
    op.add_column('data_qa', sa.Column('qa_type', sa.VARCHAR(), autoincrement=False, nullable=True,
                  comment='the type of QA processing (e.g., detectorMap, fluxCalibrate, etc.)'))
    op.add_column('data_qa', sa.Column('qa_version', sa.VARCHAR(
    ), autoincrement=False, nullable=True, comment='QA code version (e.g., xxxxx)'))
    op.drop_column('data_qa', 'process_type')
    op.drop_column('data_qa', 'drp_qa_version')
    op.drop_column('data_qa', 'pipe2d_version')
    op.create_table('detector_map',
                    sa.Column('run_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('spectrograph', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('arm', sa.VARCHAR(length=1),
                              autoincrement=False, nullable=False),
                    sa.Column('residual_wavelength_mean', sa.REAL(), autoincrement=False, nullable=True,
                              comment='the mean wavelength residual averaged over fibers (nm)'),
                    sa.Column('residual_wavelength_median', sa.REAL(), autoincrement=False, nullable=True,
                              comment='the median wavelength residual averaged over fibers (nm)'),
                    sa.Column('residual_wavelength_sigma', sa.REAL(), autoincrement=False, nullable=True,
                              comment='the sigma of the wavelength residual averaged over fibers (nm)'),
                    sa.Column('residual_trace_mean', sa.REAL(), autoincrement=False, nullable=True,
                              comment='the mean wavelength residual averaged over fibers (nm)'),
                    sa.Column('residual_trace_median', sa.REAL(), autoincrement=False, nullable=True,
                              comment='the median wavelength residual averaged over fibers (nm)'),
                    sa.Column('residual_trace_sigma', sa.REAL(), autoincrement=False, nullable=True,
                              comment='the sigma of the wavelength residual averaged over fibers (nm)'),
                    sa.ForeignKeyConstraint(
                        ['run_id'], ['data_qa.run_id'], name=op.f('detector_map_run_id_fkey')),
                    sa.PrimaryKeyConstraint('run_id', 'spectrograph',
                                            'arm', name=op.f('detector_map_pkey')),
                    sa.UniqueConstraint('run_id', 'spectrograph', 'arm', name=op.f(
                        'detector_map_run_id_spectrograph_arm_key'))
                    )
    op.create_table('flux_calibration',
                    sa.Column('run_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('spectrograph', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('arm', sa.VARCHAR(length=1),
                              autoincrement=False, nullable=False),
                    sa.Column('number_of_flux_standards', sa.INTEGER(), autoincrement=False, nullable=True,
                              comment='the number of flux standard stars to calculate the vector'),
                    sa.Column('tbd', sa.REAL(), autoincrement=False,
                              nullable=True, comment='TBD'),
                    sa.ForeignKeyConstraint(['run_id'], ['data_qa.run_id'], name=op.f(
                        'flux_calibration_run_id_fkey')),
                    sa.PrimaryKeyConstraint('run_id', 'spectrograph',
                                            'arm', name=op.f('flux_calibration_pkey')),
                    sa.UniqueConstraint('run_id', 'spectrograph', 'arm', name=op.f(
                        'flux_calibration_run_id_spectrograph_arm_key'))
                    )
    op.create_table('sky_subtraction',
                    sa.Column('run_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('spectrograph', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('arm', sa.VARCHAR(length=1),
                              autoincrement=False, nullable=False),
                    sa.Column('number_of_sky_fibers', sa.INTEGER(), autoincrement=False,
                              nullable=True, comment='the number of sky fibers to make the sky model'),
                    sa.Column('residual_chi_mean', sa.REAL(), autoincrement=False, nullable=True,
                              comment='the mean sky subtraction residual in chi averaged over FoV (counts)'),
                    sa.Column('residual_chi_median', sa.REAL(), autoincrement=False, nullable=True,
                              comment='the median sky subtraction residual in chi averaged over FoV (counts)'),
                    sa.Column('residual_chi_sigma', sa.REAL(), autoincrement=False, nullable=True,
                              comment='the sigma of the sky subtraction residual in chi (counts)'),
                    sa.ForeignKeyConstraint(['run_id'], ['data_qa.run_id'], name=op.f(
                        'sky_subtraction_run_id_fkey')),
                    sa.PrimaryKeyConstraint('run_id', 'spectrograph',
                                            'arm', name=op.f('sky_subtraction_pkey')),
                    sa.UniqueConstraint('run_id', 'spectrograph', 'arm', name=op.f(
                        'sky_subtraction_run_id_spectrograph_arm_key'))
                    )
    op.create_table('data_processing',
                    sa.Column('run_id', sa.INTEGER(), server_default=sa.text(
                        "nextval('data_processing_run_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('pfs_visit_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('drp_id', sa.INTEGER(), autoincrement=False,
                              nullable=True, comment='DRPxD to process the data (x=1/2)'),
                    sa.Column('drp_version', sa.VARCHAR(), autoincrement=False, nullable=True,
                              comment='DRP version (e.g., w.2023.20 (DRP2D), 0.40.0 (DRP1D) )'),
                    sa.Column('process_type', sa.VARCHAR(), autoincrement=False, nullable=True,
                              comment='the type of DRP processing (e.g., reduceExposure, mergeArms, etc.)'),
                    sa.Column('process_datetime_start', postgresql.TIMESTAMP(
                    ), autoincrement=False, nullable=True, comment='datetime of the processing run start'),
                    sa.Column('process_datetime_end', postgresql.TIMESTAMP(
                    ), autoincrement=False, nullable=True, comment='datetime of the processing run end'),
                    sa.ForeignKeyConstraint(['pfs_visit_id'], [
                        'pfs_visit.pfs_visit_id'], name='data_processing_pfs_visit_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'run_id', name='data_processing_pkey'),
                    sa.UniqueConstraint(
                        'run_id', name='data_processing_run_id_key'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('data_processing_results',
                    sa.Column('run_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('tbd', sa.REAL(), autoincrement=False,
                              nullable=True, comment='TBD'),
                    sa.ForeignKeyConstraint(['run_id'], ['data_processing.run_id'], name=op.f(
                        'data_processing_results_run_id_fkey')),
                    sa.PrimaryKeyConstraint('run_id', name=op.f(
                        'data_processing_results_pkey'))
                    )
    op.drop_table('sky_subtraction_qa_sa_line')
    op.drop_table('sky_subtraction_qa_sa_continuum')
    op.drop_table('sky_subtraction_qa_sa')
    op.drop_table('flux_cal_qa')
    op.drop_table('extraction_qa')
    op.drop_table('detector_map_qa')
    op.drop_table('data_processing_pipe2d')
    # ### end Alembic commands ###
