"""add wavelength_ref

Revision ID: 19c1f5726036
Revises: cede04a8dd36
Create Date: 2023-11-30 14:35:58.331037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c1f5726036'
down_revision: Union[str, None] = 'cede04a8dd36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noise', sa.Column('wavelength_ref', sa.REAL(), nullable=True, comment='the reference wavelength to measure the sky background noise (nm)'))
    op.add_column('seeing', sa.Column('wavelength_ref', sa.REAL(), nullable=True, comment='the reference wavelength to measure the seeing (nm)'))
    op.add_column('throughput', sa.Column('wavelength_ref', sa.REAL(), nullable=True, comment='the reference wavelength to measure the total throughput (nm)'))
    op.alter_column('throughput', 'throughput_mean',
               existing_type=sa.REAL(),
               comment='the total throughput (mean)',
               existing_comment='the instrumental throughput (mean)',
               existing_nullable=True)
    op.alter_column('throughput', 'throughput_median',
               existing_type=sa.REAL(),
               comment='the total throughput (median)',
               existing_comment='the instrumental throughput (median)',
               existing_nullable=True)
    op.alter_column('throughput', 'throughput_sigma',
               existing_type=sa.REAL(),
               comment='the total throughput (sigma)',
               existing_comment='the instrumental throughput (sigma)',
               existing_nullable=True)
    op.add_column('transparency', sa.Column('wavelength_ref', sa.REAL(), nullable=True, comment='the reference wavelength to measure the transparency (nm)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transparency', 'wavelength_ref')
    op.alter_column('throughput', 'throughput_sigma',
               existing_type=sa.REAL(),
               comment='the instrumental throughput (sigma)',
               existing_comment='the total throughput (sigma)',
               existing_nullable=True)
    op.alter_column('throughput', 'throughput_median',
               existing_type=sa.REAL(),
               comment='the instrumental throughput (median)',
               existing_comment='the total throughput (median)',
               existing_nullable=True)
    op.alter_column('throughput', 'throughput_mean',
               existing_type=sa.REAL(),
               comment='the instrumental throughput (mean)',
               existing_comment='the total throughput (mean)',
               existing_nullable=True)
    op.drop_column('throughput', 'wavelength_ref')
    op.drop_column('seeing', 'wavelength_ref')
    op.drop_column('noise', 'wavelength_ref')
    # ### end Alembic commands ###
