"""test

Revision ID: 80b2a58946a7
Revises: 
Create Date: 2023-11-16 13:44:42.875734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b2a58946a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cobra_convergence', ['pfs_visit_id'])
    op.create_unique_constraint(None, 'cosmic_rays', ['run_id', 'spectrograph', 'arm'])
    op.create_unique_constraint(None, 'data_processing', ['run_id'])
    op.create_unique_constraint(None, 'data_qa', ['run_id'])
    op.create_unique_constraint(None, 'detector_map', ['run_id', 'spectrograph', 'arm'])
    op.create_unique_constraint(None, 'dichroic_continuity', ['run_id', 'spectrograph'])
    op.create_unique_constraint(None, 'exposure_time', ['pfs_visit_id'])
    op.create_unique_constraint(None, 'flux_calibration', ['run_id', 'spectrograph', 'arm'])
    op.create_unique_constraint(None, 'guide_offset', ['pfs_visit_id'])
    op.create_unique_constraint(None, 'h4_persistence', ['run_id', 'spectrograph'])
    op.create_unique_constraint(None, 'mask', ['run_id', 'spectrograph', 'arm'])
    op.create_unique_constraint(None, 'moon', ['pfs_visit_id'])
    op.create_unique_constraint(None, 'noise', ['pfs_visit_id'])
    op.create_unique_constraint(None, 'pfs_visit', ['pfs_visit_id'])
    op.create_unique_constraint(None, 'seeing', ['pfs_visit_id'])
    op.create_unique_constraint(None, 'sky', ['pfs_visit_id'])
    op.create_unique_constraint(None, 'sky_subtraction', ['run_id', 'spectrograph', 'arm'])
    op.create_unique_constraint(None, 'telescope', ['pfs_visit_id'])
    op.create_unique_constraint(None, 'test', ['test_id'])
    op.create_unique_constraint(None, 'throughput', ['pfs_visit_id'])
    op.create_unique_constraint(None, 'transparency', ['pfs_visit_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transparency', type_='unique')
    op.drop_constraint(None, 'throughput', type_='unique')
    op.drop_constraint(None, 'test', type_='unique')
    op.drop_constraint(None, 'telescope', type_='unique')
    op.drop_constraint(None, 'sky_subtraction', type_='unique')
    op.drop_constraint(None, 'sky', type_='unique')
    op.drop_constraint(None, 'seeing', type_='unique')
    op.drop_constraint(None, 'pfs_visit', type_='unique')
    op.drop_constraint(None, 'noise', type_='unique')
    op.drop_constraint(None, 'moon', type_='unique')
    op.drop_constraint(None, 'mask', type_='unique')
    op.drop_constraint(None, 'h4_persistence', type_='unique')
    op.drop_constraint(None, 'guide_offset', type_='unique')
    op.drop_constraint(None, 'flux_calibration', type_='unique')
    op.drop_constraint(None, 'exposure_time', type_='unique')
    op.drop_constraint(None, 'dichroic_continuity', type_='unique')
    op.drop_constraint(None, 'detector_map', type_='unique')
    op.drop_constraint(None, 'data_qa', type_='unique')
    op.drop_constraint(None, 'data_processing', type_='unique')
    op.drop_constraint(None, 'cosmic_rays', type_='unique')
    op.drop_constraint(None, 'cobra_convergence', type_='unique')
    # ### end Alembic commands ###
