"""add agc_background_*

Revision ID: cede04a8dd36
Revises: 80b2a58946a7
Create Date: 2023-11-16 15:00:19.299892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cede04a8dd36'
down_revision: Union[str, None] = '80b2a58946a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sky', sa.Column('agc_background_mean', sa.REAL(), nullable=True, comment='the mean agc image background level averaged over the FoV/fibers (counts)'))
    op.add_column('sky', sa.Column('agc_background_median', sa.REAL(), nullable=True, comment='the median agc image background level averaged over the FoV/fibers (counts)'))
    op.add_column('sky', sa.Column('agc_background_sigma', sa.REAL(), nullable=True, comment='the sigma of the agc image background level (counts)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sky', 'agc_background_sigma')
    op.drop_column('sky', 'agc_background_median')
    op.drop_column('sky', 'agc_background_mean')
    # ### end Alembic commands ###
